[package]
name = "stroop-emu-mem"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
process-memory = "0.5"
sysinfo = "0.33"
thiserror = "2"
